apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy: 
  kubectl: {}
build:
  local:
    push: false
  artifacts:
      - image: bin19095/auth
        context: auth
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
      - image: bin19095/clients1
        context: client
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: '**/*.js'
              dest: .
      - image: bin19095/tickets
        context: tickets
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.ts'
              dest: .
