apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: tickets
deploy: 
  kubectl:
    manifests:
      - ./infra/k8s/*  # Includes client-depl.yaml and other YAML files in the infra/k8s directory
build:
  local:
    push: false
  artifacts:
    - image: bin19095/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: bin19095/clients1
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: bin19095/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: bin19095/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
